name: Cypress Tests
run: npx cypress run --config-file cypress.config.ts

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress.io
        uses: Cypress-io/github-action@v2
        with:
          start: npm start