name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:  # Set environment variables
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress.io
        uses: Cypress-io/github-action@v6
        with:
          start: npm start
